/**
 * @summary
 * Creates a new automation suggestion generated by the AI system.
 * 
 * @procedure spAutomationSuggestionCreate
 * @schema functional
 * @type stored-procedure
 * 
 * @endpoints
 * - POST /api/v1/internal/automation-suggestion
 * 
 * @parameters
 * @param {INT} idAccount
 *   - Required: Yes
 *   - Description: Account identifier for multi-tenancy
 * 
 * @param {INT} idUser
 *   - Required: Yes
 *   - Description: User identifier who will receive the suggestion
 * 
 * @param {VARCHAR} suggestionType
 *   - Required: Yes
 *   - Description: Type of suggestion (RECURRING_TASK, TASK_FROM_INTEGRATION, TAG_SUGGESTION, PROJECT_SUGGESTION)
 * 
 * @param {NVARCHAR} sourceContent
 *   - Required: No
 *   - Description: Original content that triggered the suggestion
 * 
 * @param {NVARCHAR} suggestedActionPayload
 *   - Required: Yes
 *   - Description: JSON payload containing the suggested action details
 * 
 * @returns {INT} idSuggestion - The ID of the newly created suggestion
 * 
 * @testScenarios
 * - Valid creation with all required parameters
 * - Validation failure for invalid suggestion type
 * - Validation failure for non-existent user
 * - Validation failure for invalid account
 */
CREATE OR ALTER PROCEDURE [functional].[spAutomationSuggestionCreate]
  @idAccount INTEGER,
  @idUser INTEGER,
  @suggestionType VARCHAR(50),
  @sourceContent NVARCHAR(MAX) = NULL,
  @suggestedActionPayload NVARCHAR(MAX)
AS
BEGIN
  SET NOCOUNT ON;

  /**
   * @validation Validate required parameters
   * @throw {parameterRequired}
   */
  IF (@idAccount IS NULL)
  BEGIN
    ;THROW 51000, 'idAccountRequired', 1;
  END;

  IF (@idUser IS NULL)
  BEGIN
    ;THROW 51000, 'idUserRequired', 1;
  END;

  IF (@suggestionType IS NULL OR @suggestionType = '')
  BEGIN
    ;THROW 51000, 'suggestionTypeRequired', 1;
  END;

  IF (@suggestedActionPayload IS NULL OR @suggestedActionPayload = '')
  BEGIN
    ;THROW 51000, 'suggestedActionPayloadRequired', 1;
  END;

  /**
   * @validation Validate suggestion type enumeration
   * @throw {invalidSuggestionType}
   */
  IF (@suggestionType NOT IN ('RECURRING_TASK', 'TASK_FROM_INTEGRATION', 'TAG_SUGGESTION', 'PROJECT_SUGGESTION'))
  BEGIN
    ;THROW 51000, 'invalidSuggestionType', 1;
  END;

  /**
   * @validation Validate user exists and belongs to account
   * @throw {userDoesntExist}
   */
  IF NOT EXISTS (
    SELECT 1 
    FROM [security].[user] usr
    WHERE usr.[idUser] = @idUser 
      AND usr.[idAccount] = @idAccount
  )
  BEGIN
    ;THROW 51000, 'userDoesntExist', 1;
  END;

  BEGIN TRY
    BEGIN TRAN;

      DECLARE @idSuggestion INTEGER;

      /**
       * @rule {db-multi-tenancy-pattern} Insert suggestion with account isolation
       */
      INSERT INTO [functional].[automationSuggestion] (
        [idAccount],
        [idUser],
        [suggestionType],
        [sourceContent],
        [suggestedActionPayload],
        [status],
        [dateCreated],
        [dateModified]
      )
      VALUES (
        @idAccount,
        @idUser,
        @suggestionType,
        @sourceContent,
        @suggestedActionPayload,
        'PENDING',
        GETUTCDATE(),
        GETUTCDATE()
      );

      SET @idSuggestion = SCOPE_IDENTITY();

      /**
       * @output {SuggestionCreated, 1, 1}
       * @column {INT} idSuggestion
       * - Description: The ID of the newly created suggestion
       */
      SELECT @idSuggestion AS [idSuggestion];

    COMMIT TRAN;
  END TRY
  BEGIN CATCH
    ROLLBACK TRAN;
    THROW;
  END CATCH;
END;
GO
